'use client'
import { Inter } from "next/font/google";
import { Provider } from "react-redux";
import { store } from "@/redux store/store.js";
import { PersistGate } from 'redux-persist/integration/react';

import "./globals.css";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";

import { storePersistance, persistor } from "@/redux store/storePersistance.js";

import Navbar from "@/components/Navbar and Footer/Navbar.jsx";
import Footer from "@/components/Navbar and Footer/Footer.jsx";

config.autoAddCss = false;

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Provider store={store}> */}
        <Provider store={storePersistance}>
          <Navbar />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
